# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class ProductScraperItem(scrapy.Item):
    shop_url = scrapy.Field()
    shop_name = scrapy.Field()
    # shop_description = scrapy.Field()
    shop_location = scrapy.Field()
    shop_status = scrapy.Field()
    profile_url = scrapy.Field()
    products_count = scrapy.Field()
    feedbacks_count = scrapy.Field()
    feedbacks_url = scrapy.Field()
    policy_url = scrapy.Field()
    blog_url = scrapy.Field()
    blogs_count = scrapy.Field()
    folowers_url = scrapy.Field()
    folowers_count = scrapy.Field()
    # shop_rating = scrapy.Field()
    shop_img = scrapy.Field()
    products_name = scrapy.Field()
    products_url = scrapy.Field()
    product_price = scrapy.Field()
    product_discount = scrapy.Field()
    product_old_price = scrapy.Field()
    count_product_sales = scrapy.Field()
    count_product_likes = scrapy.Field()
    product_material = scrapy.Field()
    product_size = scrapy.Field()
    product_description = scrapy.Field()
    product_care = scrapy.Field()
    master_name = scrapy.Field()
    master_url = scrapy.Field()
    master_location = scrapy.Field()
    master_status = scrapy.Field()
    terms_return = scrapy.Field()
    product_img = scrapy.Field()
    category_url = scrapy.Field()


class OskellyScraperItem(scrapy.Item):
    shop_name = scrapy.Field()
    profile_url = scrapy.Field()
    shop_img = scrapy.Field()
    how_long = scrapy.Field()
    seller_type = scrapy.Field()
    products_count = scrapy.Field()
    followers_count = scrapy.Field()
    follows_count = scrapy.Field()
    verified_icon = scrapy.Field()

    products_url = scrapy.Field()
    products_name = scrapy.Field()
    brands_name = scrapy.Field()
    short_info = scrapy.Field()
    product_price = scrapy.Field()
    product_old_price = scrapy.Field()
    product_discount = scrapy.Field()
    master_name = scrapy.Field()
    short_about_seller = scrapy.Field()
    master_url = scrapy.Field()
    product_description = scrapy.Field()
    section = scrapy.Field()
    category = scrapy.Field()
    color = scrapy.Field()
    product_condition = scrapy.Field()
    oskelly_id = scrapy.Field()
    size_type = scrapy.Field()
    product_size = scrapy.Field()
    vintage = scrapy.Field()
    product_material = scrapy.Field()
    bracelet = scrapy.Field()
    mechanism = scrapy.Field()
    have_box = scrapy.Field()
    product_images = scrapy.Field()
    category_url = scrapy.Field()


class AmazonScrapperItem(scrapy.Item):
    # define the fields for your item here like:
    products_url = scrapy.Field()
    products_title = scrapy.Field()
    shop_name = scrapy.Field()
    shop_link = scrapy.Field()
    category_url = scrapy.Field()
    price = scrapy.Field()
    max_price = scrapy.Field()
    price_currency = scrapy.Field()
    products_old_price = scrapy.Field()
    products_discount = scrapy.Field()
    subscription_discount = scrapy.Field()
    subscription_price = scrapy.Field()
    installments = scrapy.Field()
    short_info = scrapy.Field()
    about_this_item = scrapy.Field()
    technical_details = scrapy.Field()
    features = scrapy.Field()
    brand = scrapy.Field()
    model = scrapy.Field()
    image_urls = scrapy.Field()
    other_sellers = scrapy.Field()


class ErosScrapperItem(scrapy.Item):
    # define the fields for your item here like:
    products_url = scrapy.Field()
    products_title = scrapy.Field()
    model = scrapy.Field()
    highlights = scrapy.Field()
    price = scrapy.Field()
    products_old_price = scrapy.Field()
    products_discount = scrapy.Field()
    warranty = scrapy.Field()
    technical_details = scrapy.Field()
    img_urls = scrapy.Field()
    category_url = scrapy.Field()


class AeScrapperItem(scrapy.Item):
    brands_url = scrapy.Field()
    brands_name = scrapy.Field()
    brands_main_photo = scrapy.Field()
    brands_description = scrapy.Field()
    products_count = scrapy.Field()
    products_url = scrapy.Field()
    products_title = scrapy.Field()
    shop_link = scrapy.Field()
    shop_name = scrapy.Field()
    price = scrapy.Field()
    price_currency = scrapy.Field()
    products_old_price = scrapy.Field()
    products_discount = scrapy.Field()
    products_color = scrapy.Field()
    products_size = scrapy.Field()
    products_availability = scrapy.Field()
    products_description = scrapy.Field()
    products_detail = scrapy.Field()
    products_ingredients = scrapy.Field()
    about_products_brand = scrapy.Field()
    size_fit = scrapy.Field()
    product_code = scrapy.Field()
    product_master_id = scrapy.Field()
    img_urls = scrapy.Field()
    category_url = scrapy.Field()


class CategoriesItem(scrapy.Item):
    name = scrapy.Field()
    url = scrapy.Field()
    categories = scrapy.Field()
